//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_App.WCF_Movie_Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Movie_Services.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovieByIdActor", ReplyAction="http://tempuri.org/IService1/GetMovieByIdActorResponse")]
        DTO.MovieDTO[] GetMovieByIdActor(int idActor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMovieByIdActor", ReplyAction="http://tempuri.org/IService1/GetMovieByIdActorResponse")]
        System.Threading.Tasks.Task<DTO.MovieDTO[]> GetMovieByIdActorAsync(int idActor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFavoriteFilms", ReplyAction="http://tempuri.org/IService1/GetFavoriteFilmsResponse")]
        DTO.LightMovieDTO[] GetFavoriteFilms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFavoriteFilms", ReplyAction="http://tempuri.org/IService1/GetFavoriteFilmsResponse")]
        System.Threading.Tasks.Task<DTO.LightMovieDTO[]> GetFavoriteFilmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCharacterByIdActorAndIdFilm", ReplyAction="http://tempuri.org/IService1/GetCharacterByIdActorAndIdFilmResponse")]
        DTO.CharacterDTO[] GetCharacterByIdActorAndIdFilm(int actorId, int MovieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCharacterByIdActorAndIdFilm", ReplyAction="http://tempuri.org/IService1/GetCharacterByIdActorAndIdFilmResponse")]
        System.Threading.Tasks.Task<DTO.CharacterDTO[]> GetCharacterByIdActorAndIdFilmAsync(int actorId, int MovieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindXMoviesByPartialActorName", ReplyAction="http://tempuri.org/IService1/FindXMoviesByPartialActorNameResponse")]
        DTO.MovieDTO[] FindXMoviesByPartialActorName(string name, int nbElm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindXMoviesByPartialActorName", ReplyAction="http://tempuri.org/IService1/FindXMoviesByPartialActorNameResponse")]
        System.Threading.Tasks.Task<DTO.MovieDTO[]> FindXMoviesByPartialActorNameAsync(string name, int nbElm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCommentOnActorId", ReplyAction="http://tempuri.org/IService1/InsertCommentOnActorIdResponse")]
        void InsertCommentOnActorId(int actorId, DTO.CommentDTO commentDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCommentOnActorId", ReplyAction="http://tempuri.org/IService1/InsertCommentOnActorIdResponse")]
        System.Threading.Tasks.Task InsertCommentOnActorIdAsync(int actorId, DTO.CommentDTO commentDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActorById", ReplyAction="http://tempuri.org/IService1/GetActorByIdResponse")]
        DTO.FullActorDTO GetActorById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActorById", ReplyAction="http://tempuri.org/IService1/GetActorByIdResponse")]
        System.Threading.Tasks.Task<DTO.FullActorDTO> GetActorByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountActors", ReplyAction="http://tempuri.org/IService1/GetCountActorsResponse")]
        int GetCountActors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCountActors", ReplyAction="http://tempuri.org/IService1/GetCountActorsResponse")]
        System.Threading.Tasks.Task<int> GetCountActorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXActorsFromY", ReplyAction="http://tempuri.org/IService1/GetXActorsFromYResponse")]
        DTO.ActorDTO[] GetXActorsFromY(int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXActorsFromY", ReplyAction="http://tempuri.org/IService1/GetXActorsFromYResponse")]
        System.Threading.Tasks.Task<DTO.ActorDTO[]> GetXActorsFromYAsync(int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXActorsByName", ReplyAction="http://tempuri.org/IService1/GetXActorsByNameResponse")]
        DTO.ActorDTO[] GetXActorsByName(string name, int X);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXActorsByName", ReplyAction="http://tempuri.org/IService1/GetXActorsByNameResponse")]
        System.Threading.Tasks.Task<DTO.ActorDTO[]> GetXActorsByNameAsync(string name, int X);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCommentByActorId", ReplyAction="http://tempuri.org/IService1/GetCommentByActorIdResponse")]
        DTO.CommentDTO[] GetCommentByActorId(int actorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCommentByActorId", ReplyAction="http://tempuri.org/IService1/GetCommentByActorIdResponse")]
        System.Threading.Tasks.Task<DTO.CommentDTO[]> GetCommentByActorIdAsync(int actorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountCommentsByActor", ReplyAction="http://tempuri.org/IService1/CountCommentsByActorResponse")]
        int CountCommentsByActor(int actorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountCommentsByActor", ReplyAction="http://tempuri.org/IService1/CountCommentsByActorResponse")]
        System.Threading.Tasks.Task<int> CountCommentsByActorAsync(int actorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXCommentsFromYByActorId", ReplyAction="http://tempuri.org/IService1/GetXCommentsFromYByActorIdResponse")]
        DTO.CommentDTO[] GetXCommentsFromYByActorId(int actorId, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetXCommentsFromYByActorId", ReplyAction="http://tempuri.org/IService1/GetXCommentsFromYByActorIdResponse")]
        System.Threading.Tasks.Task<DTO.CommentDTO[]> GetXCommentsFromYByActorIdAsync(int actorId, int X, int Y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WPF_App.WCF_Movie_Services.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WPF_App.WCF_Movie_Services.IService1>, WPF_App.WCF_Movie_Services.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTO.MovieDTO[] GetMovieByIdActor(int idActor) {
            return base.Channel.GetMovieByIdActor(idActor);
        }
        
        public System.Threading.Tasks.Task<DTO.MovieDTO[]> GetMovieByIdActorAsync(int idActor) {
            return base.Channel.GetMovieByIdActorAsync(idActor);
        }
        
        public DTO.LightMovieDTO[] GetFavoriteFilms() {
            return base.Channel.GetFavoriteFilms();
        }
        
        public System.Threading.Tasks.Task<DTO.LightMovieDTO[]> GetFavoriteFilmsAsync() {
            return base.Channel.GetFavoriteFilmsAsync();
        }
        
        public DTO.CharacterDTO[] GetCharacterByIdActorAndIdFilm(int actorId, int MovieId) {
            return base.Channel.GetCharacterByIdActorAndIdFilm(actorId, MovieId);
        }
        
        public System.Threading.Tasks.Task<DTO.CharacterDTO[]> GetCharacterByIdActorAndIdFilmAsync(int actorId, int MovieId) {
            return base.Channel.GetCharacterByIdActorAndIdFilmAsync(actorId, MovieId);
        }
        
        public DTO.MovieDTO[] FindXMoviesByPartialActorName(string name, int nbElm) {
            return base.Channel.FindXMoviesByPartialActorName(name, nbElm);
        }
        
        public System.Threading.Tasks.Task<DTO.MovieDTO[]> FindXMoviesByPartialActorNameAsync(string name, int nbElm) {
            return base.Channel.FindXMoviesByPartialActorNameAsync(name, nbElm);
        }
        
        public void InsertCommentOnActorId(int actorId, DTO.CommentDTO commentDTO) {
            base.Channel.InsertCommentOnActorId(actorId, commentDTO);
        }
        
        public System.Threading.Tasks.Task InsertCommentOnActorIdAsync(int actorId, DTO.CommentDTO commentDTO) {
            return base.Channel.InsertCommentOnActorIdAsync(actorId, commentDTO);
        }
        
        public DTO.FullActorDTO GetActorById(int id) {
            return base.Channel.GetActorById(id);
        }
        
        public System.Threading.Tasks.Task<DTO.FullActorDTO> GetActorByIdAsync(int id) {
            return base.Channel.GetActorByIdAsync(id);
        }
        
        public int GetCountActors() {
            return base.Channel.GetCountActors();
        }
        
        public System.Threading.Tasks.Task<int> GetCountActorsAsync() {
            return base.Channel.GetCountActorsAsync();
        }
        
        public DTO.ActorDTO[] GetXActorsFromY(int X, int Y) {
            return base.Channel.GetXActorsFromY(X, Y);
        }
        
        public System.Threading.Tasks.Task<DTO.ActorDTO[]> GetXActorsFromYAsync(int X, int Y) {
            return base.Channel.GetXActorsFromYAsync(X, Y);
        }
        
        public DTO.ActorDTO[] GetXActorsByName(string name, int X) {
            return base.Channel.GetXActorsByName(name, X);
        }
        
        public System.Threading.Tasks.Task<DTO.ActorDTO[]> GetXActorsByNameAsync(string name, int X) {
            return base.Channel.GetXActorsByNameAsync(name, X);
        }
        
        public DTO.CommentDTO[] GetCommentByActorId(int actorId) {
            return base.Channel.GetCommentByActorId(actorId);
        }
        
        public System.Threading.Tasks.Task<DTO.CommentDTO[]> GetCommentByActorIdAsync(int actorId) {
            return base.Channel.GetCommentByActorIdAsync(actorId);
        }
        
        public int CountCommentsByActor(int actorId) {
            return base.Channel.CountCommentsByActor(actorId);
        }
        
        public System.Threading.Tasks.Task<int> CountCommentsByActorAsync(int actorId) {
            return base.Channel.CountCommentsByActorAsync(actorId);
        }
        
        public DTO.CommentDTO[] GetXCommentsFromYByActorId(int actorId, int X, int Y) {
            return base.Channel.GetXCommentsFromYByActorId(actorId, X, Y);
        }
        
        public System.Threading.Tasks.Task<DTO.CommentDTO[]> GetXCommentsFromYByActorIdAsync(int actorId, int X, int Y) {
            return base.Channel.GetXCommentsFromYByActorIdAsync(actorId, X, Y);
        }
    }
}
